# Project content for the portfolio. Edit here, then run: python tools/build.py
# group: mern | python | django
# screens: (kind, caption)  kind in dash chat map cal table flow cards player kanban doc video
# roadmap: (phase, typical duration, [tasks])

PROJECTS = [
{
 "slug": "podagain", "group": "mern", "tag": "Featured · MERN + AI", "icon": "pod", "bg": "a", "featured": True,
 "name": "PodAgain: AI Learning & Podcast Platform",
 "cat": "MERN · Python · Celery · AWS EC2 · AI",
 "short": "Podcasts, blogs, PDFs and documents turned into a searchable knowledge base, then into a two-person AI podcast. Rebuilt from a blocking prototype into a queue-based platform with GPU servers that start and stop on demand.",
 "bullets": ["Celery job pipelines for transcription, embeddings and audio generation", "Qwen voices instead of ElevenLabs, Pinecone search, AssemblyAI transcripts", "Subscriptions plus per-minute usage credits"],
 "stack": ["React", "Node / Express", "MongoDB", "Python", "Celery", "Redis", "AWS EC2 (GPU)", "Pinecone", "AssemblyAI", "Qwen"],
 "overview": "PodAgain is an AI-powered learning platform that turns long-form content into interactive, conversational audio. Users add podcast RSS feeds, blogs, PDFs and documents. The platform processes and indexes them, so users can later ask questions or give a prompt and generate a two-person AI podcast based on what they have learned.",
 "problem": "The project arrived as a largely vibe-coded prototype. APIs were synchronous and blocking, so every expensive AI operation was tied to a single user request, and there was no real infrastructure for long-running AI workloads. The GPU server did far more than GPU work and ran around the clock.",
 "outcomes": [("4", "content sources: RSS, blogs, PDFs and documents"), ("GPU on demand", "server starts for AI jobs and stops when idle"), ("Credits", "subscriptions plus per-minute usage billing")],
 "features": [
  ("Queue-based job system", "Celery workers replaced blocking requests for ingestion, transcription, content processing, embeddings, vector indexing and audio generation."),
  ("Leaner GPU server", "Business logic moved out of the Python AI server and into the main backend, so the expensive GPU instance only does GPU work."),
  ("Smart GPU scheduling", "The AWS EC2 GPU instance starts when a job needs it and shuts down after a configurable idle period."),
  ("Open-source voices", "ElevenLabs was replaced with Qwen-based generation for the conversational two-host podcast audio."),
  ("Credits and billing", "Subscription tiers plus usage-based minute credits for transcription, AI voice and audio processing."),
  ("Retrieval pipeline", "AssemblyAI transcripts and document text are embedded into Pinecone for semantic search across everything a user has added."),
  ("Frontend overhaul", "A refreshed interface and a product that now goes well beyond its original podcast-only workflow."),
 ],
 "flow": [("Frontend", "React app"), ("Node / Express backend", "auth, billing, business logic"), ("Job queue", "Celery + Redis"), ("Worker processes", "ingest, transcribe, embed"), ("AI / GPU infrastructure", "started on demand"), ("Vector database", "Pinecone")],
 "flownote": "Long-running workloads run independently of user-facing requests, and GPU spend follows actual usage.",
 "roadmap": [
  ("Audit the prototype", "1 week", ["Map every blocking endpoint and where GPU time was spent", "List content sources and the target user flows", "Agree what moves out of the AI server"]),
  ("Queue architecture", "1-2 weeks", ["Introduce Celery and Redis alongside the Node backend", "Define job types, retries and status reporting", "Move business logic from the Python AI server into the backend"]),
  ("Ingestion and retrieval", "2-3 weeks", ["RSS, blog, PDF and document ingestion jobs", "AssemblyAI transcription and text processing", "Embedding generation and Pinecone indexing, with semantic search"]),
  ("GPU scheduling and audio", "2 weeks", ["Start/stop automation for the EC2 GPU instance with an idle timer", "Swap ElevenLabs for Qwen two-host audio generation", "Prompt-to-podcast generation end to end"]),
  ("Credits, UI and launch", "2 weeks", ["Subscription tiers and minute-based credits", "Frontend overhaul across the new content types", "Monitoring, load testing and production rollout"]),
 ],
 "screens": [("player", "Generated two-host podcast with transcript"), ("table", "Learning library: feeds, blogs, PDFs, documents"), ("flow", "Background job pipeline and GPU status")],
},
{
 "slug": "ai-support-copilot", "group": "mern", "tag": "MERN + AI", "icon": "chat", "bg": "a",
 "name": "AI Support Copilot for Knowledge Bases", "cat": "MERN · Python · Pinecone · LLM",
 "short": "A React front end and Node API over a Python retrieval service. Teams upload help-centre articles, PDFs and past tickets; agents get cited answers and suggested replies inside the ticket view.",
 "bullets": ["Ingestion runs as queued jobs, so large uploads never block the app", "Answers cite the source passage, so agents can check before sending", "Per-workspace indexes keep each customer's data separate"],
 "stack": ["React", "Node / Express", "MongoDB", "Python", "Pinecone", "Redis"],
 "overview": "A support-team copilot. Companies connect their help centre, PDFs and past tickets; the system indexes them and, inside the ticket view, suggests a reply with the exact source passages it relied on, so an agent can approve, edit or discard it.",
 "problem": "Support agents spend most of their time searching old tickets and docs for the same answers, and generic chatbots invent answers that can't be checked. Teams needed suggestions they could trust and trace back to a source.",
 "outcomes": [("Cited", "every suggested answer links to its source passage"), ("Per-workspace", "separate index and access for each customer"), ("Async", "large uploads processed in the background")],
 "features": [("Document ingestion", "Help-centre pages, PDFs and past tickets are chunked, embedded and indexed through queued jobs."), ("Cited answers", "Replies show the passages they were built from, with links back to the original document."), ("Reply drafting", "Agents get a draft in the ticket view and can accept, edit or discard it in one click."), ("Workspace isolation", "Each customer's content lives in its own index with role-based access."), ("Feedback loop", "Accepted and edited replies feed a quality dashboard that shows where the knowledge base has gaps.")],
 "flow": [("React agent UI", "ticket view and reply panel"), ("Node / Express API", "auth, workspaces, tickets"), ("Job queue", "ingestion and re-indexing"), ("Python retrieval service", "chunking, embeddings, ranking"), ("Pinecone", "per-workspace vector index"), ("LLM", "grounded reply drafting")],
 "flownote": "Retrieval and generation sit behind the API, so the app stays fast while indexing runs in the background.",
 "roadmap": [("Discovery", "1 week", ["Review the help centre, ticket volume and common questions", "Choose chunking and retrieval approach", "Define success: accepted-reply rate and handling time"]), ("Foundations", "1-2 weeks", ["Workspace and user model, auth and roles", "Ticket view in React", "Queue and storage setup"]), ("Retrieval engine", "2-3 weeks", ["Ingestion jobs for docs, PDFs and tickets", "Embedding and Pinecone indexing per workspace", "Citation-aware answer generation"]), ("Agent experience", "2 weeks", ["Reply drafting inside the ticket view", "Feedback capture and quality dashboard", "Prompt and retrieval tuning on real tickets"]), ("Launch", "1 week", ["Pilot with one team, then widen", "Monitoring, rate limits and cost tracking", "Handover documentation"])],
 "screens": [("chat", "Ticket view with a cited, suggested reply"), ("table", "Knowledge sources and indexing status"), ("dash", "Quality dashboard: accepted vs edited replies")],
},
{
 "slug": "booking-subscription-platform", "group": "mern", "tag": "MERN", "icon": "cal", "bg": "b",
 "name": "Multi-Tenant Booking & Subscription Platform", "cat": "MERN · Stripe · Socket.io",
 "short": "A white-label booking SaaS: each business gets its own branded site, staff calendars, deposits and recurring plans, all on one codebase.",
 "bullets": ["Tenant-aware API with role-based access for owners, staff and clients", "Live calendar updates over WebSockets, no refresh needed", "Webhook-driven billing with retries and an audit trail"],
 "stack": ["React", "Node / Express", "MongoDB", "Stripe", "Socket.io", "AWS"],
 "overview": "A booking platform that many businesses use as their own. Each tenant gets a branded booking site, staff calendars, services and pricing, deposits and recurring membership plans, while the team maintains a single codebase.",
 "problem": "Small service businesses juggle calendars, payment links and spreadsheets, and off-the-shelf tools either look generic or charge per seat. The goal was a branded, subscription-ready booking product that onboards a new business in minutes.",
 "outcomes": [("1 codebase", "serves every tenant with its own branding"), ("Live", "calendar changes appear instantly for everyone"), ("Audited", "every payment event is logged and retried safely")],
 "features": [("Tenant branding", "Logo, colours, domain and booking rules per business."), ("Staff calendars", "Availability, breaks, services and buffers per team member."), ("Deposits and plans", "One-off deposits and recurring memberships through Stripe."), ("Live updates", "Socket.io keeps calendars in sync across staff and client screens."), ("Roles and access", "Owner, staff and client roles with tenant-scoped data."), ("Billing events", "Webhook handling with idempotency, retries and an audit trail.")],
 "flow": [("React apps", "client booking, staff, owner"), ("Node / Express API", "tenant-aware, role-based"), ("MongoDB", "tenant-scoped collections"), ("Socket.io", "live calendar events"), ("Stripe", "payments, plans, webhooks"), ("AWS", "hosting, storage, email")],
 "flownote": "Every query is scoped by tenant, so one deployment safely serves many businesses.",
 "roadmap": [("Discovery", "1 week", ["Map the booking journey for each business type", "Decide the tenancy model and branding limits", "List payment and plan rules"]), ("Core booking", "2-3 weeks", ["Services, staff and availability engine", "Booking flow and confirmations", "Tenant onboarding"]), ("Payments", "2 weeks", ["Deposits and refunds in Stripe", "Recurring plans and failed-payment handling", "Webhook processing with an audit trail"]), ("Realtime and admin", "2 weeks", ["Socket.io live calendar", "Owner dashboard and reports", "Notifications by email and SMS"]), ("Launch", "1 week", ["Load and permission testing", "Pilot tenants", "Documentation and support setup"])],
 "screens": [("cal", "Staff calendar with live bookings"), ("cards", "Services and membership plans"), ("dash", "Owner dashboard: revenue and bookings")],
},
{
 "slug": "logistics-dispatch-dashboard", "group": "mern", "tag": "MERN", "icon": "truck", "bg": "a",
 "name": "Live Logistics & Dispatch Dashboard", "cat": "MERN · Maps · Real-time",
 "short": "Dispatchers see every vehicle and job on one live map. Drivers update status from a mobile web view, and customers get tracking links.",
 "bullets": ["Event stream for location and status, batched to stay light on the database", "Route and ETA views for dispatchers, simple status taps for drivers", "Exportable job history and proof-of-delivery"],
 "stack": ["React", "Node / Express", "MongoDB", "Socket.io", "Mapbox", "Docker"],
 "overview": "A dispatch console for delivery and field-service fleets. One live map shows vehicles, jobs and ETAs; drivers update status from a lightweight mobile web view; customers follow their delivery from a tracking link.",
 "problem": "Dispatch ran on phone calls and spreadsheets. Nobody could see where vehicles were, customers kept calling for ETAs, and proof of delivery was scattered across chat messages.",
 "outcomes": [("1 map", "all vehicles, jobs and ETAs live"), ("Tracking links", "customers stop calling for updates"), ("POD", "proof of delivery stored with each job")],
 "features": [("Live map", "Vehicle positions and job states update in real time."), ("Job assignment", "Drag a job onto a driver, with route and ETA suggestions."), ("Driver web view", "Large status buttons, navigation hand-off and photo capture."), ("Customer tracking", "A shareable link with live status and ETA."), ("Proof of delivery", "Photo, signature and timestamp stored with the job."), ("History and exports", "Filter by driver, date or status and export to CSV.")],
 "flow": [("Driver web view", "location and status taps"), ("Node / Express API", "jobs, drivers, auth"), ("Event stream", "Socket.io, batched writes"), ("MongoDB", "jobs, events, POD"), ("Dispatcher console", "React + Mapbox"), ("Tracking page", "customer link")],
 "flownote": "Location pings are batched before they reach the database, so the live view stays fast as the fleet grows.",
 "roadmap": [("Discovery", "1 week", ["Shadow dispatchers and drivers", "Define job states and ETA rules", "Pick map and routing provider"]), ("Data and API", "1-2 weeks", ["Job, driver and vehicle models", "Auth and roles", "Event ingestion and batching"]), ("Dispatcher console", "2-3 weeks", ["Live map with filters", "Assignment and re-assignment", "Route and ETA panels"]), ("Driver and customer views", "2 weeks", ["Mobile status flow with photo and signature", "Customer tracking page", "Notifications"]), ("Launch", "1 week", ["Field test with a small fleet", "Reports and CSV exports", "Rollout and training"])],
 "screens": [("map", "Live map with vehicles and routes"), ("table", "Job list with status and ETA"), ("kanban", "Dispatch board by job state")],
},
{
 "slug": "restaurant-ordering-kds", "group": "mern", "tag": "MERN", "icon": "dish", "bg": "b",
 "name": "Restaurant Ordering & Kitchen Display System", "cat": "MERN · Socket.io · Stripe",
 "short": "Customers order from a QR code at the table or online. Orders appear instantly on kitchen screens, and the front of house sees status and takes payment.",
 "bullets": ["Real-time order tickets by station, with timers and bump buttons", "Menu, modifiers and availability managed by the restaurant", "Multi-location accounts with per-site reports"],
 "stack": ["React", "Node / Express", "MongoDB", "Socket.io", "Stripe", "PWA"],
 "overview": "A QR-code ordering system with a kitchen display. Guests scan, order and pay at the table or online; tickets show up instantly on the right kitchen station; staff track status from a tablet.",
 "problem": "Paper tickets and shouted orders caused mistakes and slow tables, and third-party ordering apps took a large cut and owned the customer relationship.",
 "outcomes": [("Instant", "orders reach the right station in real time"), ("Table or online", "one menu, two ways to order"), ("Multi-site", "reports per location")],
 "features": [("QR table ordering", "Guests order and pay from their phone, no app to install."), ("Kitchen display", "Tickets by station with timers, bump buttons and recall."), ("Menu management", "Categories, modifiers, allergens and live availability."), ("Payments", "Card payments and split bills through Stripe."), ("Staff tablet", "Table status, call-waiter alerts and order edits."), ("Multi-location", "Owner view across sites with sales and prep-time reports.")],
 "flow": [("Guest PWA", "menu, cart, pay"), ("Node / Express API", "orders, menu, auth"), ("Socket.io", "ticket events"), ("Kitchen display", "per-station screens"), ("MongoDB", "orders and menus"), ("Stripe", "payments")],
 "flownote": "Order events fan out over WebSockets, so the kitchen, floor and guest all see the same status.",
 "roadmap": [("Discovery", "1 week", ["Map the service flow and stations", "Menu and modifier structure", "Payment and tip rules"]), ("Ordering app", "2 weeks", ["Guest PWA with QR table codes", "Cart, modifiers and checkout", "Menu admin"]), ("Kitchen and floor", "2 weeks", ["Real-time kitchen display", "Staff tablet view", "Printer fallback"]), ("Multi-location", "1-2 weeks", ["Tenant and site model", "Reports and exports", "Role permissions"]), ("Launch", "1 week", ["Soft launch in one venue", "Peak-hour load testing", "Staff training"])],
 "screens": [("cards", "Guest menu on a phone, with modifiers"), ("kanban", "Kitchen display: new, preparing, ready"), ("dash", "Owner reports: sales and prep time")],
},
{
 "slug": "property-listings-marketplace", "group": "mern", "tag": "MERN", "icon": "home", "bg": "a",
 "name": "Property Listings Marketplace", "cat": "MERN · Maps · Search",
 "short": "Agents publish listings with photo galleries; buyers search on a map with filters, save searches and send enquiries straight to the agent.",
 "bullets": ["Map and filter search with saved searches and email alerts", "Agent dashboard for listings, enquiries and viewings", "Image upload pipeline with automatic resizing"],
 "stack": ["React", "Node / Express", "MongoDB", "Mapbox", "Cloudinary", "Redis"],
 "overview": "A property marketplace where agents manage listings and buyers search on a map. Saved searches send alerts, enquiries go straight to the agent, and viewings are scheduled in the platform.",
 "problem": "Listings lived on separate portals with slow, cluttered search, and enquiries got lost in email. The client wanted their own marketplace, with fast map search and a clear agent workflow.",
 "outcomes": [("Map search", "filter and browse by area"), ("Alerts", "saved searches email new matches"), ("Pipeline", "enquiries tracked from first message to viewing")],
 "features": [("Map and filters", "Price, bedrooms, type and area with instant results."), ("Listing management", "Rich listings with galleries, floor plans and status."), ("Saved searches", "Buyers get email alerts for new matching listings."), ("Enquiry inbox", "Agents see enquiries, reply and book viewings."), ("Image pipeline", "Uploads are resized and optimised automatically."), ("Admin", "Moderation, featured listings and agency accounts.")],
 "flow": [("React site", "search and listing pages"), ("Node / Express API", "listings, users, enquiries"), ("MongoDB", "geo-indexed listings"), ("Redis", "cached searches, alerts queue"), ("Cloudinary", "image storage and resizing"), ("Email service", "alerts and enquiries")],
 "flownote": "Geo-indexed queries and cached filters keep map search quick as listings grow.",
 "roadmap": [("Discovery", "1 week", ["Define listing fields and agent roles", "Map and search requirements", "SEO needs for listing pages"]), ("Listings core", "2 weeks", ["Listing models and agent dashboard", "Image upload pipeline", "Moderation tools"]), ("Search", "2 weeks", ["Map and filter search", "Saved searches and alerts", "SEO-friendly listing pages"]), ("Enquiries", "1-2 weeks", ["Enquiry inbox and replies", "Viewing scheduling", "Notifications"]), ("Launch", "1 week", ["Data import from the old portal", "Performance tuning", "Rollout"])],
 "screens": [("map", "Map search with listing cards"), ("cards", "Listing grid with filters"), ("table", "Agent enquiries inbox")],
},
{
 "slug": "telehealth-video-consult", "group": "mern", "tag": "MERN", "icon": "video", "bg": "b",
 "name": "Telehealth Appointment & Video Consult Platform", "cat": "MERN · WebRTC · Stripe",
 "short": "Patients book a slot, pay, and join a video consultation from the browser. Clinicians get a calendar, notes and follow-up prompts.",
 "bullets": ["Browser-based video rooms with waiting-room and reminders", "Role-based access, with session notes visible only to the care team", "Payments and invoices tied to each appointment"],
 "stack": ["React", "Node / Express", "MongoDB", "WebRTC", "Twilio", "Stripe"],
 "overview": "A telehealth platform for clinics. Patients choose a clinician and slot, pay online and join a video room from the browser. Clinicians get a calendar, secure notes and follow-up prompts.",
 "problem": "Clinics were using a mix of phone calls, generic video links and manual invoices. Patients got lost between steps, and notes lived in personal documents.",
 "outcomes": [("Browser video", "no app install for patients"), ("Pay first", "payment tied to each appointment"), ("Private", "notes visible only to the care team")],
 "features": [("Booking", "Clinician availability, slots and service types."), ("Video rooms", "WebRTC consultations with a waiting room."), ("Reminders", "Email and SMS reminders reduce no-shows."), ("Clinical notes", "Secure notes per session with role-based access."), ("Payments", "Card payment and invoices per appointment."), ("Follow-ups", "Prompts and re-booking after each consultation.")],
 "flow": [("Patient web app", "book, pay, join"), ("Node / Express API", "auth, roles, scheduling"), ("WebRTC + TURN", "video sessions"), ("MongoDB", "appointments, notes"), ("Stripe", "payments and invoices"), ("Twilio", "SMS reminders")],
 "flownote": "Access control is enforced in the API, so notes and recordings never reach anyone outside the care team.",
 "roadmap": [("Discovery", "1 week", ["Clinical workflow and consent requirements", "Compliance and data-handling review", "Pick video and SMS providers"]), ("Scheduling and auth", "2 weeks", ["Clinician availability and booking", "Roles and permissions", "Reminders"]), ("Video consults", "2-3 weeks", ["WebRTC rooms and waiting room", "Connection quality handling", "Session notes"]), ("Payments", "1-2 weeks", ["Payment at booking and refunds", "Invoices", "Follow-up prompts"]), ("Launch", "1 week", ["Security and permission testing", "Pilot clinic", "Support runbook"])],
 "screens": [("video", "Video consultation with notes panel"), ("cal", "Clinician calendar"), ("table", "Patient appointments and payments")],
},
{
 "slug": "invoicing-expense-saas", "group": "mern", "tag": "MERN", "icon": "receipt", "bg": "a",
 "name": "Invoicing & Expense SaaS", "cat": "MERN · Stripe · PDF",
 "short": "Freelancers and small teams create branded invoices, accept card payments, track expenses and see cash flow in one dashboard.",
 "bullets": ["Recurring invoices and automatic payment reminders", "Receipt uploads with categories and monthly summaries", "Client portal where invoices can be viewed and paid"],
 "stack": ["React", "Node / Express", "MongoDB", "Stripe", "Redis", "AWS S3"],
 "overview": "A small-business finance tool. Users create branded invoices, accept card payments, upload receipts, categorise expenses and see their cash flow at a glance. Clients pay from a simple portal.",
 "problem": "Freelancers were stitching together spreadsheets, PDF templates and payment links, and chasing late payments by hand.",
 "outcomes": [("Paid online", "clients pay from the invoice link"), ("Automatic", "reminders and recurring invoices"), ("One view", "income, expenses and cash flow")],
 "features": [("Branded invoices", "Templates with logo, tax and currency settings."), ("Online payment", "Card payments with automatic reconciliation."), ("Recurring and reminders", "Scheduled invoices and polite payment nudges."), ("Expenses", "Receipt uploads, categories and monthly summaries."), ("Client portal", "View, download and pay invoices."), ("Reports", "Profit, outstanding invoices and tax-ready exports.")],
 "flow": [("React app", "dashboard and invoices"), ("Node / Express API", "auth, invoices, expenses"), ("Job queue", "recurring and reminders"), ("MongoDB", "accounts and ledgers"), ("Stripe", "payments"), ("S3 + PDF service", "receipts and invoice PDFs")],
 "flownote": "Scheduled work runs in a queue, so reminders and recurring invoices go out reliably.",
 "roadmap": [("Discovery", "1 week", ["Invoice fields, tax and currency rules", "Payment flow and fees", "Report requirements"]), ("Invoicing core", "2 weeks", ["Clients, items and invoice builder", "PDF generation and email", "Stripe payments"]), ("Automation", "1-2 weeks", ["Recurring invoices", "Reminder schedule", "Reconciliation"]), ("Expenses and reports", "2 weeks", ["Receipt upload and categories", "Cash-flow dashboard", "Exports"]), ("Launch", "1 week", ["Security review", "Onboarding flow", "Billing for the SaaS itself"])],
 "screens": [("dash", "Cash-flow dashboard"), ("doc", "Branded invoice preview"), ("table", "Invoices: paid, due and overdue")],
},
{
 "slug": "amazon-price-seller-monitor", "group": "python", "tag": "Python", "icon": "tag", "bg": "b",
 "name": "Amazon Price & Seller Monitor", "cat": "Python · Playwright · PostgreSQL",
 "short": "A scheduled pipeline that tracks price, stock, Buy Box owner and seller count for a list of Amazon listings, and alerts the team when something moves.",
 "bullets": ["Rotating sessions and retry logic to cope with layout changes and blocks", "History table for trend charts and daily change reports", "Alert rules per product: price drop, stock-out, new seller"],
 "stack": ["Python", "Playwright", "Proxies", "PostgreSQL", "Celery", "Slack / Email"],
 "overview": "A monitoring pipeline for Amazon sellers and brands. It checks a list of listings on a schedule, stores every price, stock and Buy Box change, and alerts the team when something important moves.",
 "problem": "Checking competitors and unauthorised sellers by hand was slow and always late. Prices changed several times a day and the team only noticed after sales dropped.",
 "outcomes": [("Scheduled", "every listing checked on its own cadence"), ("History", "every change stored for trends"), ("Alerts", "price, stock and seller changes pushed to the team")],
 "features": [("Listing tracking", "Price, stock, Buy Box owner, seller count and rating."), ("Resilient collection", "Rotating sessions, retries and layout-change detection."), ("Change history", "Every observation stored for charts and audits."), ("Alert rules", "Per-product rules for drops, stock-outs and new sellers."), ("Reports", "Daily summaries by email or Slack."), ("API and export", "CSV and API access for other tools.")],
 "flow": [("Scheduler", "Celery beat"), ("Collectors", "Python + Playwright"), ("Proxy pool", "rotating sessions"), ("PostgreSQL", "listings and history"), ("Rules engine", "change detection"), ("Slack / Email", "alerts and reports")],
 "flownote": "Collection, storage and alerting are separate steps, so a blocked page never loses data already collected.",
 "roadmap": [("Scope", "3-5 days", ["List the ASINs and fields to track", "Agree cadence and alert rules", "Review terms and allowed use"]), ("Collector", "1-2 weeks", ["Playwright collectors with retries", "Session and proxy handling", "Parsing and validation"]), ("Storage and rules", "1 week", ["PostgreSQL schema and history", "Change detection", "Alert rules"]), ("Reporting", "1 week", ["Slack and email alerts", "Daily summary report", "CSV and API"]), ("Hardening", "1 week", ["Monitoring of the monitor", "Layout-change alarms", "Handover and runbook"])],
 "screens": [("table", "Tracked listings with price and Buy Box"), ("dash", "Price history and seller count"), ("flow", "Collection and alert pipeline")],
},
{
 "slug": "walmart-catalogue-scraper", "group": "python", "tag": "Python", "icon": "cart", "bg": "a",
 "name": "Walmart Catalogue & Pricing Scraper", "cat": "Python · Scrapy · FastAPI",
 "short": "Collects product, price, availability and review data for chosen categories and sellers, normalises it and serves it through a private API and scheduled CSV exports.",
 "bullets": ["Category and keyword crawls with de-duplication across runs", "Cleaned, typed fields ready for BI tools or a repricer", "Run reports show coverage, failures and how long each crawl took"],
 "stack": ["Python", "Scrapy", "FastAPI", "PostgreSQL", "Docker", "AWS"],
 "overview": "A data-collection service for Walmart marketplace listings. It crawls chosen categories, keywords and sellers, cleans and de-duplicates the results and serves them through a private API and scheduled exports.",
 "problem": "The client needed catalogue and pricing data in a consistent shape, but raw page data was messy, changed often and arrived with duplicates across crawls.",
 "outcomes": [("Normalised", "typed, consistent fields across runs"), ("De-duplicated", "no repeats between crawls"), ("API + CSV", "data ready for BI or repricing")],
 "features": [("Targeted crawls", "By category, keyword, seller or product list."), ("Normalisation", "Consistent price, availability and attribute fields."), ("De-duplication", "Stable product keys across runs."), ("Private API", "FastAPI endpoints with filtering and pagination."), ("Scheduled exports", "CSV drops to storage on a schedule."), ("Run reports", "Coverage, failures and timing for every crawl.")],
 "flow": [("Crawl definitions", "categories, sellers, keywords"), ("Scrapy spiders", "collection and retries"), ("Cleaning pipeline", "typing and de-duplication"), ("PostgreSQL", "products and prices"), ("FastAPI", "private data API"), ("Exports + reports", "CSV, run summaries")],
 "flownote": "Spiders only collect; a separate pipeline cleans and validates, so bad data is caught before it reaches the API.",
 "roadmap": [("Scope", "3-5 days", ["Target categories, sellers and fields", "Volume and freshness requirements", "Review terms and allowed use"]), ("Spiders", "1-2 weeks", ["Category and keyword crawlers", "Retry and throttling", "Pagination handling"]), ("Pipeline", "1 week", ["Cleaning and typing", "De-duplication keys", "PostgreSQL schema"]), ("API and exports", "1 week", ["FastAPI endpoints", "Scheduled CSV exports", "Auth for API clients"]), ("Operations", "1 week", ["Run reports and alerts", "Docker and AWS deployment", "Handover"])],
 "screens": [("table", "Collected catalogue with normalised fields"), ("flow", "Crawl, clean and serve pipeline"), ("dash", "Run report: coverage and failures")],
},
{
 "slug": "cross-marketplace-repricer", "group": "python", "tag": "Python", "icon": "bars", "bg": "b",
 "name": "Cross-Marketplace Repricing Engine", "cat": "Python · Pandas · APIs",
 "short": "Combines Amazon and Walmart price feeds with your own cost data and rules to propose or push new prices, with guardrails on minimum margin.",
 "bullets": ["Rule engine: match, undercut or hold, within a margin floor", "Dry-run mode shows the effect before anything is changed", "Every price change is logged with the rule that caused it"],
 "stack": ["Python", "Pandas", "FastAPI", "PostgreSQL", "Celery", "Redis"],
 "overview": "A repricing engine for marketplace sellers. It reads competitor prices from Amazon and Walmart, applies your cost data and strategy rules, and proposes or pushes new prices, never below your margin floor.",
 "problem": "Manual repricing couldn't keep up with competitor changes, and simple tools either undercut blindly or ignored costs, eroding margin.",
 "outcomes": [("Margin floor", "no price below the minimum margin"), ("Dry run", "preview changes before they go live"), ("Traceable", "each change linked to its rule")],
 "features": [("Strategy rules", "Match, undercut, hold or follow a target Buy Box."), ("Margin guardrails", "Cost, fees and minimum margin per SKU."), ("Dry-run mode", "See the effect of rules before pushing prices."), ("Feed submission", "Push approved prices back to the marketplaces."), ("Change log", "Who or what changed each price, and why."), ("Dashboard", "Prices, margins and rule hit-rates.")],
 "flow": [("Competitor feeds", "Amazon and Walmart data"), ("Cost data", "SKU costs and fees"), ("Rule engine", "pandas + strategies"), ("Approval / dry run", "review before push"), ("Feed submission", "marketplace APIs"), ("Change log", "audit trail")],
 "flownote": "Rules decide, guardrails limit, and everything is logged, so repricing stays explainable.",
 "roadmap": [("Strategy workshop", "3-5 days", ["Define repricing strategies per product group", "Margin and fee model", "Edge cases: stock-outs, no competitors"]), ("Data layer", "1-2 weeks", ["Competitor feed ingestion", "Cost and fee data", "SKU matching across marketplaces"]), ("Rule engine", "2 weeks", ["Strategy implementation", "Guardrails", "Dry-run mode"]), ("Push and audit", "1 week", ["Feed submission", "Change log", "Approval workflow"]), ("Launch", "1 week", ["Pilot on a product subset", "Dashboards", "Gradual rollout"])],
 "screens": [("dash", "Margin and price-change overview"), ("table", "Proposed vs current price per SKU"), ("flow", "Rule evaluation pipeline")],
},
{
 "slug": "invoice-document-extraction", "group": "python", "tag": "Python", "icon": "doc", "bg": "a",
 "name": "Invoice & Document Extraction Service", "cat": "Python · FastAPI · OCR",
 "short": "Upload invoices, receipts or forms and get structured JSON back. Large batches go through a queue and results are delivered by webhook.",
 "bullets": ["Per-field confidence scores, with low-confidence items flagged for review", "Idempotent API and webhooks safe to retry", "Exports to CSV or straight into your accounting tool"],
 "stack": ["Python", "FastAPI", "OCR", "LLM", "Celery", "S3"],
 "overview": "A document-processing API. Upload invoices, receipts or forms and receive structured data with confidence scores. Large batches are queued and delivered by webhook.",
 "problem": "Finance teams were keying invoice data by hand. Generic OCR returned raw text, with no structure or way to know what was uncertain.",
 "outcomes": [("Structured", "JSON fields instead of raw text"), ("Confidence", "low-certainty fields flagged for review"), ("Batch", "queue and webhook delivery")],
 "features": [("Upload API", "Single files or batches by API or dashboard."), ("OCR and extraction", "Text recognition plus LLM-assisted field extraction."), ("Confidence scores", "Per-field scores, with a review queue for uncertain ones."), ("Webhooks", "Idempotent delivery with retries."), ("Exports", "CSV or direct push to accounting tools."), ("Review UI", "Correct a field and the fix is stored for later tuning.")],
 "flow": [("Upload API", "FastAPI + S3"), ("Queue", "Celery workers"), ("OCR", "text and layout"), ("Extraction", "fields via rules + LLM"), ("Review queue", "low-confidence items"), ("Webhook / export", "structured JSON, CSV")],
 "flownote": "Every document moves through the same queued steps, so large batches scale by adding workers.",
 "roadmap": [("Document study", "3-5 days", ["Collect sample documents and layouts", "Define the target fields", "Agree accuracy targets"]), ("Extraction core", "2 weeks", ["OCR and layout parsing", "Field extraction and validation", "Confidence scoring"]), ("API and queue", "1-2 weeks", ["FastAPI endpoints and auth", "Celery batches", "Webhooks and idempotency"]), ("Review and export", "1 week", ["Review UI for low-confidence fields", "CSV and accounting integration", "Feedback storage"]), ("Launch", "1 week", ["Accuracy benchmark on real documents", "Monitoring", "Handover"])],
 "screens": [("doc", "Invoice with extracted fields highlighted"), ("table", "Batch results with confidence scores"), ("flow", "Queued extraction pipeline")],
},
{
 "slug": "school-management-system", "group": "django", "tag": "Django", "icon": "school", "bg": "b",
 "name": "School Management System", "cat": "Django · DRF · PostgreSQL",
 "short": "Admissions, attendance, timetables, fee collection, exams and report cards in one system, with separate views for admins, teachers, students and parents.",
 "bullets": ["Role-based permissions across four user types", "Fee vouchers, receipts and defaulter reports", "Report cards generated as PDFs in the background"],
 "stack": ["Django", "Django REST Framework", "PostgreSQL", "Celery", "Redis", "Docker"],
 "overview": "A complete school ERP. Admissions, classes, attendance, timetables, fee collection, exams and report cards in a single system, with tailored views for administrators, teachers, students and parents.",
 "problem": "Records lived in paper registers and disconnected spreadsheets. Fees were hard to reconcile, report cards took weeks and parents had no visibility.",
 "outcomes": [("4 roles", "admin, teacher, student, parent"), ("Fees", "vouchers, receipts and defaulters in one place"), ("PDFs", "report cards generated in the background")],
 "features": [("Admissions and records", "Student profiles, classes, sections and guardians."), ("Attendance", "Daily marking with parent notifications."), ("Timetables", "Teacher and class schedules with clash detection."), ("Fees", "Vouchers, receipts, discounts and defaulter reports."), ("Exams and results", "Mark entry, grading rules and report cards."), ("Portals", "Parent and student views of attendance, fees and results.")],
 "flow": [("Web app", "templates + DRF API"), ("Django apps", "students, fees, exams"), ("Permissions", "role-based access"), ("PostgreSQL", "relational records"), ("Celery + Redis", "PDFs, notifications"), ("Storage", "documents and photos")],
 "flownote": "Each school function is its own Django app with a shared permission layer, so modules can grow without tangling.",
 "roadmap": [("Requirements", "1-2 weeks", ["Walk the admissions-to-results cycle", "Define roles and permissions", "Fee and grading rules"]), ("Core records", "2-3 weeks", ["Students, classes and guardians", "Attendance", "Timetables"]), ("Fees", "2 weeks", ["Fee structures and vouchers", "Receipts and reconciliation", "Defaulter reports"]), ("Exams and portals", "3 weeks", ["Marks and grading", "Report-card PDFs", "Parent and student portals"]), ("Launch", "1-2 weeks", ["Data import from spreadsheets", "Training", "Go-live support"])],
 "screens": [("dash", "Admin dashboard: attendance and fees"), ("table", "Fee vouchers and defaulters"), ("doc", "Report card preview")],
},
{
 "slug": "multi-vendor-marketplace", "group": "django", "tag": "Django", "icon": "store", "bg": "a",
 "name": "Multi-Vendor Marketplace", "cat": "Django · DRF · Celery · Stripe",
 "short": "Vendors list products and manage orders, customers shop one cart across vendors, and admins control commissions and payouts.",
 "bullets": ["Split payments and commission rules per vendor", "Order and shipment status per vendor inside a single customer order", "Search and filters that stay fast on large catalogues"],
 "stack": ["Django", "DRF", "PostgreSQL", "Celery", "Stripe Connect", "Elasticsearch"],
 "overview": "A marketplace where many vendors sell through one storefront. Vendors manage products and orders, customers check out once across vendors, and admins control commissions and payouts.",
 "problem": "Selling through generic platforms meant no control over commissions or vendor onboarding, and multi-seller carts and split payouts were not supported.",
 "outcomes": [("1 cart", "many vendors, one checkout"), ("Split", "payments divided and commissions applied"), ("Fast", "search and filters on large catalogues")],
 "features": [("Vendor onboarding", "Applications, approval and per-vendor settings."), ("Catalogue", "Products, variants, stock and media per vendor."), ("Multi-vendor cart", "One checkout that splits into vendor orders."), ("Split payments", "Stripe Connect payouts with commission rules."), ("Order management", "Per-vendor fulfilment and shipment status."), ("Search", "Elasticsearch-powered search and filters.")],
 "flow": [("Storefront", "customer web app"), ("Django apps", "catalogue, orders, vendors"), ("DRF API", "storefront and vendor dashboards"), ("PostgreSQL", "orders and payouts"), ("Elasticsearch", "product search"), ("Stripe Connect + Celery", "split payments, payouts")],
 "flownote": "A customer order splits into vendor sub-orders, each with its own fulfilment and payout.",
 "roadmap": [("Requirements", "1-2 weeks", ["Vendor and customer journeys", "Commission and payout rules", "Catalogue structure"]), ("Catalogue and vendors", "3 weeks", ["Vendor onboarding and dashboards", "Products, variants and stock", "Media handling"]), ("Cart and orders", "3 weeks", ["Multi-vendor cart and checkout", "Order splitting", "Fulfilment statuses"]), ("Payments and search", "2-3 weeks", ["Stripe Connect and commissions", "Elasticsearch search", "Payout reports"]), ("Launch", "2 weeks", ["Load testing", "Admin tools and moderation", "Go-live"])],
 "screens": [("cards", "Storefront with products from many vendors"), ("table", "Vendor orders and payouts"), ("dash", "Admin: commissions and sales")],
},
{
 "slug": "inventory-order-management", "group": "django", "tag": "Django", "icon": "box", "bg": "b",
 "name": "Inventory & Order Management System", "cat": "Django · PostgreSQL · REST",
 "short": "Multi-warehouse stock, purchase orders, sales orders and invoicing for a distributor, with barcode scanning and low-stock reordering.",
 "bullets": ["Stock ledger so every movement can be traced", "Purchase-order suggestions from sales history and lead times", "Role-based approvals and a full change history"],
 "stack": ["Django", "DRF", "PostgreSQL", "Celery", "Redis", "React admin"],
 "overview": "An inventory and order system for a distributor: multiple warehouses, purchase and sales orders, invoicing and barcode scanning, with automatic reorder suggestions when stock runs low.",
 "problem": "Stock counts differed between warehouses and spreadsheets, orders were re-keyed between systems, and reordering depended on someone remembering.",
 "outcomes": [("Ledger", "every stock movement traceable"), ("Multi-warehouse", "stock by location"), ("Suggestions", "reorders proposed from sales history")],
 "features": [("Stock ledger", "Every receipt, transfer and sale recorded."), ("Multi-warehouse", "Stock, transfers and locations."), ("Purchase orders", "Suppliers, approvals and receiving."), ("Sales orders and invoices", "Order to invoice with taxes and statuses."), ("Barcode scanning", "Receiving and picking by scan."), ("Reorder suggestions", "Low-stock alerts and suggested quantities.")],
 "flow": [("Admin and scanner UI", "React + mobile scan"), ("Django apps", "stock, purchasing, sales"), ("Approvals", "role-based workflows"), ("PostgreSQL", "ledger and orders"), ("Celery + Redis", "reorder jobs, reports"), ("Invoice PDFs", "documents and emails")],
 "flownote": "Stock is never edited directly; it is always the sum of ledger entries, which keeps counts explainable.",
 "roadmap": [("Requirements", "1-2 weeks", ["Warehouse and product structure", "Order and approval flows", "Tax and invoice rules"]), ("Stock core", "3 weeks", ["Product and location models", "Stock ledger", "Transfers and adjustments"]), ("Purchasing and sales", "3 weeks", ["Purchase orders and receiving", "Sales orders and invoicing", "Approvals"]), ("Scanning and automation", "2 weeks", ["Barcode workflows", "Reorder suggestions", "Reports"]), ("Launch", "2 weeks", ["Opening stock import", "Parallel run", "Training"])],
 "screens": [("table", "Stock by warehouse and product"), ("kanban", "Orders by status"), ("dash", "Low stock and reorder suggestions")],
},
{
 "slug": "hr-leave-payroll-portal", "group": "django", "tag": "Django", "icon": "people", "bg": "a",
 "name": "HR, Leave & Payroll Portal", "cat": "Django · Celery · PostgreSQL",
 "short": "Employee records, leave and attendance, shift rosters, payroll runs and payslips, with approval flows that match how the company actually works.",
 "bullets": ["Configurable approval chains for leave and expenses", "Payroll calculation with an audit log and re-run safety", "Payslips and reports delivered by email as PDFs"],
 "stack": ["Django", "DRF", "PostgreSQL", "Celery", "Docker", "AWS"],
 "overview": "An HR portal covering employee records, leave and attendance, shift rosters, payroll runs and payslips, with configurable approval chains.",
 "problem": "HR ran on spreadsheets and email threads. Leave balances were wrong, payroll took days to calculate and approvals got lost.",
 "outcomes": [("Approvals", "configurable chains for leave and expenses"), ("Audited", "payroll runs logged and re-runnable"), ("Self-service", "employees see balances and payslips")],
 "features": [("Employee records", "Profiles, contracts and documents."), ("Leave and attendance", "Balances, requests and calendars."), ("Rosters", "Shifts, swaps and coverage."), ("Payroll", "Calculation, deductions and approvals with an audit log."), ("Payslips", "PDF payslips delivered by email."), ("Reports", "Headcount, leave and payroll summaries.")],
 "flow": [("Employee portal", "requests and payslips"), ("Django apps", "people, leave, payroll"), ("Approval engine", "configurable chains"), ("PostgreSQL", "records and audit log"), ("Celery", "payroll runs, PDFs, email"), ("Storage", "documents on AWS")],
 "flownote": "Payroll runs are repeatable and logged, so a correction means re-running with a record of what changed.",
 "roadmap": [("Requirements", "1-2 weeks", ["Policies, leave types and approval chains", "Payroll rules and deductions", "Roles and permissions"]), ("People and leave", "3 weeks", ["Employee records", "Leave balances and requests", "Attendance"]), ("Rosters and approvals", "2 weeks", ["Shift rosters", "Configurable approvals", "Notifications"]), ("Payroll", "3 weeks", ["Calculation engine", "Audit log and re-run safety", "Payslip PDFs"]), ("Launch", "2 weeks", ["Data import", "Parallel payroll run", "Training and go-live"])],
 "screens": [("cal", "Team leave calendar"), ("table", "Payroll run with totals"), ("doc", "Payslip preview")],
},
]

GROUPS = {"mern": "MERN", "python": "Python", "django": "Django"}
